### ISSUE TITLE
paprica mg, Error: Incompatible database version

### ISSUE THREAD

**Issue by blancaverag** [bowmanjeffs/paprica#39]
I haven't build the regular paprica database due to errors, but as I am interested in metagenome annotation I downloaded the paprica-mg databases and followed the instructions [here](http://www.polarmicrobes.org/?p=1596).

And there is an error stating databases versions are incompatible.

paprica-mg_run.py -i Contigs.fna -o test -ref_dir ref_genome_database -pathways F
executing DIAMOND blastx, this might take a while...
Error: Incompatible database version
Error: function Input_stream::Input_stream(const string&, bool) line 75. Error opening file /home/blanca/test.paprica-mg.nr.daa
Traceback (most recent call last):
  File "/home/programas/paprica/paprica-mg_run.py", line 134, in <module>
    diamond_df = pd.read_csv(cwd + name + '.paprica-mg.nr.txt', sep = '\t', header = None, index_col = 0)
  File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 465, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 241, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 557, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 694, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 1061, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 350, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3143)
  File "pandas/parser.pyx", line 583, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:5765)
IOError: File /home/blanca/test.paprica-mg.nr.txt does not exist

Updating diamond to diamond v0.8.24.86 does not solve the problem.

Which version of diamond was used to build them?

Thank you,

**Comment by bowmanjeffs** [comment]
Trying to reproduce now...

**Comment by bowmanjeffs** [comment]
Yep, looks like there is a database incompatibility.  I'm re-building now, will take a few.  Will comment here when new version is posted.

**Comment by bowmanjeffs** [comment]
New database up, let me know if there are any issues.  Be sure to download the updated paprica-mg.ec.csv.gz as well.

**Comment by blancaverag** [comment]
It works now, thank you.
