### ISSUE TITLE
Issues with Running ./paprica-run.sh on test.fasta 

### ISSUE THREAD

**Issue by angelwyc** [bowmanjeffs/paprica#97]
Dear Jeff, 

I am facing some problems with running the line: 
./paprica-run.sh test bacteria

This is the error message produced: 
Incorrect number of command line arguments.
Usage: cmalign [-options] <cmfile> <seqfile>

where basic options are:
  -h     : show brief help on version and usage
  -o <f> : output the alignment to file <f>, not stdout
  -g     : configure CM for global alignment [default: local]

To see more help on available options, do cmalign -h

/bin/bash: line 1: esl-alimerge: command not found
Traceback (most recent call last):
  File "/mnt/c/Program Files/WSL/paprica/paprica-place_it.py", line 1323, in <module>
    split_query_ref(cwd + query + '.clean.unique.align.sto',
  File "/mnt/c/Program Files/WSL/paprica/paprica-place_it.py", line 282, in split_query_ref
    for record in SeqIO.parse(query_alignment, 'stockholm'):
  File "/home/angelwyc/anaconda3/envs/paprica_env/lib/python3.10/site-packages/Bio/SeqIO/__init__.py", line 608, in <genexpr>
    return (r for alignment in AlignIO.parse(handle, format) for r in alignment)
  File "/home/angelwyc/anaconda3/envs/paprica_env/lib/python3.10/site-packages/Bio/AlignIO/__init__.py", line 322, in parse
    with as_handle(handle) as fp:
  File "/home/angelwyc/anaconda3/envs/paprica_env/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/angelwyc/anaconda3/envs/paprica_env/lib/python3.10/site-packages/Bio/File.py", line 72, in as_handle
    with open(handleish, mode, **kwargs) as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/angelwyc/paprica/test.bacteria.clean.unique.align.sto'

**Comment by bowmanjeffs** [comment]
Thanks for letting me know.  It looks like a few things are going on.  First, esl-alimerge isn't in your path.  Second, there seems to be a further issue with the call to cmalign, which might clear up once the path issue is fixed.  Let me know if it still gives you trouble.  I do recommend installing all dependencies as you're doing but if need be you could also consider using the Docker image.
